### ISSUE TITLE
Fetch skips handles with over 5000 friends

### ISSUE THREAD

**Issue by reinikainen** [jdevoo/nucoll#3]
Running nucoll fetch reinikainen it seems to skip fetching twitter users that have over (I think) 5000 followers. For example
`2020/03/10 10:49:21 skipping VNetworkLabs (5001 friends)`
Is there a flag that can force fetching users with over a certain number follower count?

**Comment by reinikainen** [comment]
More specifically is this a Twitter API limitation or would changing the value on this line of cmds.go 
`	const endpoint = "https://api.twitter.com/1.1/lists/members.json?slug=%s&owner_screen_name=%s&count=5000&skip_status=true"`
overcome the limitation?

**Comment by PeterTheOne** [comment]
try `-c 5002`, see: https://github.com/jdevoo/nucoll/blob/3f8bc3a0ceb21fbcbd25ca52de243f899ad92795/cmd.go#L79 .

**Comment by reinikainen** [comment]
Thanks @PeterTheOne
