### ISSUE TITLE
Generate img

### ISSUE THREAD

**Issue by barripdmx** [jdevoo/nucoll#4]
how I generate directory with the images of the followers?

Best regards
jb

**Comment by jdevoo** [comment]
Hi! This has to be done with an external tool that can read GML files. After running nucoll edgelist you would find a GML file which can be read with e.g. [Gephi](https://gephi.org/)

**Comment by PeterTheOne** [comment]
@jdevoo I think @barripdmx means the twitter profile images and not the Gephi graph images.

**Comment by barripdmx** [comment]
> Hi! This has to be done with an external tool that can read GML files. After running nucoll edgelist you would find a GML file which can be read with e.g. [Gephi](https://gephi.org/)

Yes, the part of gephi I control

**Comment by barripdmx** [comment]
> @jdevoo I think @barripdmx means the twitter profile images and not the Gephi graph images.

Yes. that is my question. With twecoll I could do it.

**Comment by jdevoo** [comment]
oh I am so sorry... Ok...
The image download is now optional. Run `nucoll init -i <handle>` to see the img directory with avatars.
Check `nucoll init --help` to see options.

**Comment by barripdmx** [comment]
> oh I am so sorry... Ok...
> The image download is now optional. Run `nucoll init -i <handle>` to see the img directory with avatars.
> Check `nucoll init --help` to see options.

run witt python?

**Comment by barripdmx** [comment]
Perfecto. Funciona en DOS con el parámetro: nucoll.exe init -i @barripdmx

Gracias.

**Comment by barripdmx** [comment]
Hi,
With the -i parameter it takes the followed not the followers.
How do I get the images of the followers?


Usage: nucoll init [-h] [i] [-m list] [-n] [-o] [-q] [-r N] screen_name
  -i    download images (default false)
  -m string
        extract member handles from list owned by screen_name
  -n    ignore mentions from .qry file (default false)
  -o    retrieve followers (default friends)
  -q    extract handles from .qry file (default screen_name)
  -r int
        tweet count limit when looking for retweets by followers

**Comment by jdevoo** [comment]
with `nucoll init -i -o barripdmx`
Note you have 19K followers so this might take a while...

**Comment by barripdmx** [comment]
Ha funcionado. :)
Solo ha tomado 14k. ¿Es normal?

Gracias.

**Comment by jdevoo** [comment]
Que bien! Estoy tambien bajandolos y le dare un vistazo. Talves por los privados...

**Comment by barripdmx** [comment]
ok

**Comment by jdevoo** [comment]
seems very wrong @barripdmx - I also ended up with 14k count and noticed duplicates in dat file. Looking into this.

**Comment by barripdmx** [comment]
Gracias. ;)

**Comment by jdevoo** [comment]
I uploaded a new version which corrects the problem. When running init, nucoll downloads ids which can be done in pages of 5000 identifiers at a time. I was initializing this loop incorrectly. As your 19k followers needed 4 pages, it repeated one block in dat and the img folder was short of 5k images.
You will have to download the new version.
Hope this works and thank you for trying and raising this problem!

**Comment by barripdmx** [comment]
It has extracted the same data. 14k.

**Comment by jdevoo** [comment]
you are running the new version? just ran it again on your handle and got 19703 images
```
$ nucoll -v
New Collection Tool v0.2 (go1.13.4 b44055c)
```

**Comment by barripdmx** [comment]
That was the problem.
All perfect!!!

Gracias :) :) :)
